# https://travis-ci.org/#!/clouderp/odoo-docker-testrunner

dist: bionic
language: python

env:
  jobs:
    - ODOO_VERSION=11
    - ODOO_VERSION=12
    - ODOO_VERSION=13

install:
  - make image

script:
  - docker images

before_deploy:
  - echo $DOCKER_ACCESS_TOKEN | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-image
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
